/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendedoresRouteImport } from './routes/vendedores'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VendedoresRoute = VendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendedores': typeof VendedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendedores': typeof VendedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/pdv': typeof PdvRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendedores': typeof VendedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/estoque'
    | '/login'
    | '/pdv'
    | '/relatorios'
    | '/vendedores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/estoque'
    | '/login'
    | '/pdv'
    | '/relatorios'
    | '/vendedores'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/estoque'
    | '/login'
    | '/pdv'
    | '/relatorios'
    | '/vendedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EstoqueRoute: typeof EstoqueRoute
  LoginRoute: typeof LoginRoute
  PdvRoute: typeof PdvRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendedoresRoute: typeof VendedoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendedores': {
      id: '/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof VendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EstoqueRoute: EstoqueRoute,
  LoginRoute: LoginRoute,
  PdvRoute: PdvRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendedoresRoute: VendedoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
